import Head from 'next/head'
import Image from 'next/image'
import { useState } from "react";
import styles from '../styles/Home.module.css'

export default function Home() {
  const [address, setAddress] = useState("");

  const getFunds = async () => {
    try {
      const response = await fetch('/api/getether', {
        method: 'POST',
        body: JSON.stringify({ address }),
        headers: {
          'Content-Type': 'application/json'
        }
      });
      if(!response.ok) return alert('Something went wrong1!');
      alert("Transaction initiated successfully!");
    } catch (err) {
      console.error(err);
      alert('Something went wrong2!');
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>d-fine Sepolia Faucet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>d-fine Sepolia Faucet</h1>

      <div
        style={{
          height: "100vh",
          width: "100vw",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <input type="text" value={address} onChange={(e) => setAddress(e.target.value)} placeholder="Enter your account address" />
        <button onClick={getFunds}>Get Sepolia Ether</button>
      </div>
    </div>
  )
}
